project:
  type: website

website:
  title: "Actuarial Science Laboratory"
  search: false
  site-url: https://aslab.com
  description: "Actuarial Science Laboratory at NEU College of Technology"
  favicon: assets/aslab/logo-as1.png
  page-navigation: true
  #back-to-top-navigation: true
  comments: 
    utterances: 
      repo: spcanelon/silvia 
      label: utterances
      theme: body-light
      issue-term: title
 
  navbar:
    logo: assets/aslab/logo-as1.png
    right:
      - text: About
        aria-label: "About"
        href: about/index.qmd
      - text: News & Events
        aria-label: "News&Events"
        href: news&events/index.qmd
      - text: Research
        aria-label: "Research"
        href: research/index.qmd  
      - text: Publications
        aria-label: "Publications"
        href: publication/index.qmd
      - text: Contact
        aria-label: "Contact"
        href: contact.qmd
  
  page-footer:
    background: "#000000"
    foreground: "#ffffff"
    border: true
  
    left: |
      <table style="color: white; height: 100%;">
        <tr>
          <td style="vertical-align: bottom; padding-right: 12px;">
            <img src="/assets/aslab/logo_as.png" alt="AS Lab Logo" style="height: 56px;">
          </td>
          <td style="vertical-align: bottom; font-size: 14px; line-height: 1.2;">
            <span style="text-transform: uppercase; font-size: 12px; font-weight: bold;">NEU College of Technology</span><br>
            <span style="font-size: 18px; font-weight: bold;">Actuarial</span><br>
            <span style="font-size: 18px; font-weight: bold;">Science</span><br>
            <span style="font-size: 18px; font-weight: bold;">Laboratory</span>
          </td>
        </tr>
      </table>
  
    center: |
      <table style="height: 100%; width: 100%;">
        <tr>
          <td style="vertical-align: bottom; text-align: left; font-size: 15px; line-height: 1.6; color: white;">
            Room 1210, A1 Building National Economics University<br>
            207 Giai Phong Street, Dong Tam Ward, Hai Ba Trung District, Hanoi, Vietnam
          </td>
        </tr>
      </table>
  
    right: |
      <table style="width: 100%; height: 100%;">
        <tr>
          <td style="vertical-align: bottom; text-align: right; font-size: 13px; color: white;">
            &copy; 2025 AS Lab.All rights reserved.
          </td>
        </tr>
      </table>


format:
  html:
    theme:
      light:
        - cosmo
        - assets/silvia-theme-light.scss
        - assets/silvia/colors-light.scss
        - assets/silvia/fonts.scss
    highlight-style:
      light: assets/silvia/a11y-light.theme
    code-link: true
    pagetitle: "{{< meta title >}}"
    lightbox: true
    toggle-theme: false
    page-layout: full

execute: 
  freeze: auto

# include-in-header: assets/silvia/umami.html
